import React from 'react'
export  const classicNovels = [
  { title: "Pride and Prejudice", author: "Jane Austen" },
  { title: "Moby-Dick", author: "Herman Melville" },
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald" },
  { title: "Crime and Punishment", author: "Fyodor Dostoevsky" },
  { title: "To Kill a Mockingbird", author: "Harper Lee" },
  { title: "1984", author: "George Orwell" },
  { title: "The Catcher in the Rye", author: "J.D. Salinger" },
  { title: "The Odyssey", author: "Homer" },
  { title: "War and Peace", author: "Leo Tolstoy" },
  { title: "The Lord of the Rings", author: "J.R.R. Tolkien" },
  { title: "The Stranger", author: "Albert Camus" },
  // Additional classic novels
  { title: "Jane Eyre", author: "Charlotte Brontë" },
  { title: "Wuthering Heights", author: "Emily Brontë" },
  { title: "Great Expectations", author: "Charles Dickens" },
  { title: "Anna Karenina", author: "Leo Tolstoy" },
  { title: "Madame Bovary", author: "Gustave Flaubert" },
  { title: "The Adventures of Huckleberry Finn", author: "Mark Twain" },
  { title: "Don Quixote", author: "Miguel de Cervantes" },
  { title: "Frankenstein", author: "Mary Shelley" },
  { title: "Brave New World", author: "Aldous Huxley" },
  { title: "Lolita", author: "Vladimir Nabokov" },
  { title: "Ulysses", author: "James Joyce" },
  { title: "The Picture of Dorian Gray", author: "Oscar Wilde" },
  { title: "The Grapes of Wrath", author: "John Steinbeck" },
  { title: "Heart of Darkness", author: "Joseph Conrad" },
  { title: "Les Misérables", author: "Victor Hugo" },
  { title: "One Hundred Years of Solitude", author: "Gabriel García Márquez" },
  { title: "Fahrenheit 451", author: "Ray Bradbury" },
  { title: "Dracula", author: "Bram Stoker" },
  { title: "A Tale of Two Cities", author: "Charles Dickens" }
];

export const booktoScreen =[    { title: "The Godfather", author: "Mario Puzo", adaptationType: "Movie" },
{ title: "Fight Club", author: "Chuck Palahniuk", adaptationType: "Movie" },
{ title: "The Shawshank Redemption", author: "Stephen King", adaptationType: "Movie" },
{ title: "Harry Potter Series", author: "J.K. Rowling", adaptationType: "Movies" },
{ title: "Game of Thrones", author: "George R.R. Martin", adaptationType: "TV Series" },
{ title: "The Handmaid's Tale", author: "Margaret Atwood", adaptationType: "TV Series" },
{ title: "The Chronicles of Narnia", author: "C.S. Lewis", adaptationType: "Movies" },
{ title: "Forrest Gump", author: "Winston Groom", adaptationType: "Movie" },
{ title: "The Martian", author: "Andy Weir", adaptationType: "Movie" },
{ title: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", adaptationType: "Movie" },
{ title: "Dune", author: "Frank Herbert", adaptationType: "Movie" },
{ title: "Gone Girl", author: "Gillian Flynn", adaptationType: "Movie" },
{ title: "Pride and Prejudice", author: "Jane Austen", adaptationType: "Multiple Movies and TV Series" },
{ title: "Little Women", author: "Louisa May Alcott", adaptationType: "Multiple Movies" },
{ title: "The Great Gatsby", author: "F. Scott Fitzgerald", adaptationType: "Multiple Movies" },
{ title: "1984", author: "George Orwell", adaptationType: "Multiple Movies" },
{ title: "Jurassic Park", author: "Michael Crichton", adaptationType: "Movies" },
{ title: "The Silence of the Lambs", author: "Thomas Harris", adaptationType: "Movie" },
{ title: "To Kill a Mockingbird", author: "Harper Lee", adaptationType: "Movie" },
{ title: "The Lord of the Rings", author: "J.R.R. Tolkien", adaptationType: "Movies" },
{ title: "The Hobbit", author: "J.R.R. Tolkien", adaptationType: "Movies" },
{ title: "The Help", author: "Kathryn Stockett", adaptationType: "Movie" },
{ title: "Schindler’s List", author: "Thomas Keneally", adaptationType: "Movie" },
{ title: "The Exorcist", author: "William Peter Blatty", adaptationType: "Movie" },
{ title: "The Shining", author: "Stephen King", adaptationType: "Movie" },
{ title: "Misery", author: "Stephen King", adaptationType: "Movie" },
{ title: "Carrie", author: "Stephen King", adaptationType: "Multiple Movies" },
{ title: "The Da Vinci Code", author: "Dan Brown", adaptationType: "Movie" },
{ title: "A Clockwork Orange", author: "Anthony Burgess", adaptationType: "Movie" },
{ title: "Doctor Zhivago", author: "Boris Pasternak", adaptationType: "Movie" },
{ title: "Blade Runner", author: "Philip K. Dick", adaptationType: "Movie (based on 'Do Androids Dream of Electric Sheep?')" },
{ title: "Trainspotting", author: "Irvine Welsh", adaptationType: "Movie" },
{ title: "American Psycho", author: "Bret Easton Ellis", adaptationType: "Movie" },
{ title: "The Green Mile", author: "Stephen King", adaptationType: "Movie" },
{ title: "The Road", author: "Cormac McCarthy", adaptationType: "Movie" },
{ title: "The Notebook", author: "Nicholas Sparks", adaptationType: "Movie" },
{ title: "No Country for Old Men", author: "Cormac McCarthy", adaptationType: "Movie" },
{ title: "Life of Pi", author: "Yann Martel", adaptationType: "Movie" }];

